package com.omepikya.commandcenter.nlp;
import java.util.HashMap;import java.util.Locale;import java.util.Map;
public class EntityExtractor {
 public Map<String,String> extract(String command){Map<String,String> e=new HashMap<>();if(command==null||command.trim().isEmpty())return e;String t=command.trim(),l=t.toLowerCase(Locale.US);app(t,l,e);comm(t,l,e);time(t,l,e);search(t,l,e);nav(t,l,e);media(l,e);return e;}
 private void app(String t,String l,Map<String,String>e){for(String p:new String[]{"open ","launch ","start "})if(l.startsWith(p)){String v=t.substring(p.length()).trim();if(!v.isEmpty())e.put("app",v);return;}}
 private void comm(String t,String l,Map<String,String>e){for(String p:new String[]{"call ","phone ","dial ","ring "})if(l.startsWith(p)){e.put("person",t.substring(p.length()).trim());e.put("communication_type","call");return;}if(l.startsWith("give ")&&l.contains(" a call")){String p=t.substring(5).trim();int i=p.toLowerCase(Locale.US).indexOf(" a call");if(i>=0)p=p.substring(0,i).trim();e.put("person",p);e.put("communication_type","call");return;}for(String p:new String[]{"send a whatsapp message to ","send whatsapp message to ","send a message to ","send message to ","send sms to ","send an sms to ","whatsapp ","message ","text ","sms "})if(l.startsWith(p)){String r=t.substring(p.length()).trim();String type=p.contains("whatsapp")?"whatsapp":"sms";int split=messageSplit(r);if(split>0){e.put("person",r.substring(0,split).trim());e.put("message",r.substring(split).trim());}else e.put("person",r);e.put("communication_type",type);return;}}
 private int messageSplit(String r){String l=r.toLowerCase(Locale.US);for(String m:new String[]{" saying "," that "," with message "," message "}){int i=l.indexOf(m);if(i>0)return i;}return -1;}
 private void time(String t,String l,Map<String,String>e){for(String w:new String[]{" at "," tomorrow"," today"," tonight"," morning"," evening"," afternoon"}){int i=l.indexOf(w);if(i>=0){String v=t.substring(Math.min(t.length(),i+(w.startsWith(" ")?1:0))).trim();if(!v.isEmpty())e.put("time",v);return;}}}
 private void search(String t,String l,Map<String,String>e){for(String p:new String[]{"search for ","search the web for ","google "})if(l.startsWith(p)){e.put("query",t.substring(p.length()).trim());return;}}
 private void nav(String t,String l,Map<String,String>e){for(String p:new String[]{"navigate to ","directions to ","direction to ","take me to ","show me the way to ","map "})if(l.startsWith(p)){e.put("destination",t.substring(p.length()).trim());return;}}
 private void media(String l,Map<String,String>e){if(l.contains("next track")||l.contains("skip track"))e.put("media_action","next");else if(l.contains("previous track"))e.put("media_action","previous");else if(l.contains("pause"))e.put("media_action","pause");else if(l.contains("resume")||l.contains("play"))e.put("media_action","play");}
}
